FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app

# Base image to build our image off of
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# setting the work directory to run subsequent add, copy, cmd, run, etc. commands from in our IMAGE
WORKDIR /src

# Copying csproj and sln files over from our source code to image
COPY HealthSquad.sln ./
COPY /BL/*.csproj ./BL/
COPY /DL/*.csproj ./DL/
COPY /Models/*.csproj ./Models/
COPY /Tests/*.csproj ./Tests/
COPY /WebAPI/*.csproj ./WebAPI/

# Before moving further, let's check our sln is able to restore all its dependencies
RUN dotnet restore

# Copying the entire folder or src code to a different directory
# COPY . .
COPY . ./

WORKDIR /src/BL
RUN dotnet build -c release -o /app

WORKDIR /src/DL
RUN dotnet build -c release -o /app

WORKDIR /src/Models
RUN dotnet build -c release -o /app

WORKDIR /src/Tests
RUN dotnet build -c release -o /app

WORKDIR /src/WebAPI
RUN dotnet build -c release -o /app

WORKDIR /src
RUN dotnet publish -c release -o /app

COPY /WebAPI/appsettings.json /app

FROM final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "WebAPI.dll"]

EXPOSE 80